export const additionalLeads = [
  {
    "id": "new-sheet-1",
    "name": "Imóveis Belém (Skye Tower/matriz)",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "91984772865",
    "email": null,
    "site": "https://www.imoveisbelem.belem.br",
    "instagram": "@imoveisbelem_oficial",
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "IB",
    "color": "lime",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "imoveisbelem.belem.br"
  },
  {
    "id": "new-sheet-2",
    "name": "Rone Imóveis (Rone Estuart)",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "91981030982",
    "email": "rone.estuar@gmail.com",
    "site": "https://www.roneimoveis.com.br",
    "instagram": "@roneestuart",
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "RI",
    "color": "orange",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "roneimoveis.com.br"
  },
  {
    "id": "new-sheet-3",
    "name": "JCarvalho Assessoria Imobiliária",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "91993863919",
    "email": null,
    "site": "https://www.jcarvalhoimobiliaria.com.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "JA",
    "color": "cyan",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "jcarvalhoimobiliaria.com.br"
  },
  {
    "id": "new-sheet-4",
    "name": "Imobiliária Abdelnor",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://abdelnorimob.com",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "IA",
    "color": "pink",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "abdelnorimob.com"
  },
  {
    "id": "new-sheet-5",
    "name": "Mirante Portfólio Imobiliário",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "91989948329",
    "email": null,
    "site": "https://www.miranteportfolio.com.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "MP",
    "color": "violet",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "miranteportfolio.com.br"
  },
  {
    "id": "new-sheet-6",
    "name": "Moura Corretora (A. Moura Gestor Imobiliário)",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://www.mouracorretora.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "MC",
    "color": "blue",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "mouracorretora.com.br"
  },
  {
    "id": "new-sheet-7",
    "name": "Casal Águia Especialistas Imobiliário",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://www.casalaguiaimoveis.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "CÁ",
    "color": "lime",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "casalaguiaimoveis.com.br"
  },
  {
    "id": "new-sheet-8",
    "name": "Rede Apecasa",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://www.redeapecasa.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "RA",
    "color": "orange",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "redeapecasa.com.br"
  },
  {
    "id": "new-sheet-9",
    "name": "Mirian F. Imóveis (Mirian Favacho)",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "91988468883",
    "email": null,
    "site": "https://www.mirianfimoveis.com.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Visualização 3D de imóveis",
    "initials": "MF",
    "color": "cyan",
    "service": "Visualização 3D de imóveis",
    "demo": false,
    "source": "mirianfimoveis.com.br"
  },
  {
    "id": "new-sheet-10",
    "name": "O'Limpo Distribuidora e Atacado de Produtos de Limpeza",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://olimpodist.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Catálogo digital B2B com pedido via WhatsApp",
    "initials": "OD",
    "color": "pink",
    "service": "Catálogo digital B2B com pedido via WhatsApp",
    "demo": false,
    "source": "olimpodist.com.br"
  },
  {
    "id": "new-sheet-11",
    "name": "BP Distribuidora (Unidade Belém)",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://bpdistribuidora.com.br/belem",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Catálogo digital B2B com pedido via WhatsApp",
    "initials": "BD",
    "color": "violet",
    "service": "Catálogo digital B2B com pedido via WhatsApp",
    "demo": false,
    "source": "bpdistribuidora.com.br"
  },
  {
    "id": "new-sheet-12",
    "name": "SPJ Comércio e Distribuição",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "9193853333",
    "email": null,
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Catálogo digital B2B com pedido via WhatsApp",
    "initials": "SC",
    "color": "blue",
    "service": "Catálogo digital B2B com pedido via WhatsApp",
    "demo": false,
    "source": "distribuidorasdealimentos.com.br"
  },
  {
    "id": "new-sheet-13",
    "name": "Estrela do Norte Distribuidora",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "9183450050",
    "email": "contabilidade@denorte.com.br",
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Catálogo digital B2B com pedido via WhatsApp",
    "initials": "ED",
    "color": "lime",
    "service": "Catálogo digital B2B com pedido via WhatsApp",
    "demo": false,
    "source": "distribuidorasdealimentos.com.br"
  },
  {
    "id": "new-sheet-14",
    "name": "Esperanza Comércio",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "9132129675",
    "email": "esperanzamedfarma@outlook.com",
    "site": "http://www.viajeboaesperanca.com.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Catálogo digital B2B com pedido via WhatsApp",
    "initials": "EC",
    "color": "orange",
    "service": "Catálogo digital B2B com pedido via WhatsApp",
    "demo": false,
    "source": "distribuidorasdealimentos.com.br"
  },
  {
    "id": "new-sheet-15",
    "name": "Distribuidora J Maia",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "9137120305",
    "email": "televendas@distribuidorajmaia.com.br",
    "site": "http://www.distribuidorajmaia.com.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Catálogo digital B2B com pedido via WhatsApp",
    "initials": "DJ",
    "color": "cyan",
    "service": "Catálogo digital B2B com pedido via WhatsApp",
    "demo": false,
    "source": "distribuidorajmaia.com.br"
  },
  {
    "id": "new-sheet-16",
    "name": "Costa & Santos Advocacia e Consultoria Jurídica",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "91991805557",
    "email": "escritoriocostaesantos.adv@gmail.com",
    "site": "https://escritoriocsadvocacia.com",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "C&",
    "color": "pink",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "escritoriocsadvocacia.com"
  },
  {
    "id": "new-sheet-17",
    "name": "Alves e Morelli Sociedade de Advogados",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://alvesemorelli.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "AE",
    "color": "violet",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "alvesemorelli.com.br"
  },
  {
    "id": "new-sheet-18",
    "name": "Puga & Lima Advocacia",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://pugalimaadvocacia.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "P&",
    "color": "blue",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "pugalimaadvocacia.com.br"
  },
  {
    "id": "new-sheet-19",
    "name": "Arrais & Oliveira Advogados",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "",
    "email": null,
    "site": "https://arraisoliveira.com.br",
    "instagram": null,
    "priority": "Média",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "A&",
    "color": "lime",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "arraisoliveira.com.br"
  },
  {
    "id": "new-sheet-20",
    "name": "C Correa Serviços Contábeis (CEC)",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "9132499768",
    "email": "cec@ceccont.com.br",
    "site": "https://www.cec.cnt.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "CC",
    "color": "orange",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "gbrasilcontabilidade.com.br"
  },
  {
    "id": "new-sheet-21",
    "name": "GS Contadores (unidade adicional)",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "91984845676",
    "email": null,
    "site": "https://gscontadores.com.br",
    "instagram": null,
    "priority": "Alta",
    "score": 84,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "GC",
    "color": "cyan",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "gscontadores.com.br"
  },
  {
    "id": "new-sheet-22",
    "name": "Consaúde",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "9131834300",
    "email": null,
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "C",
    "color": "pink",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "cebes.com.br"
  },
  {
    "id": "new-sheet-23",
    "name": "Clínica dos Acidentados",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "9132426285",
    "email": null,
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "CD",
    "color": "violet",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "ubs.med.br"
  },
  {
    "id": "new-sheet-24",
    "name": "Cuidados Pet em Domicílio",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "91982322593",
    "email": null,
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "CP",
    "color": "blue",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "banhoetosapetpertodemim.com"
  },
  {
    "id": "new-sheet-25",
    "name": "Pet Shop Campeão",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "91982022959",
    "email": null,
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "PS",
    "color": "lime",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "petshoppertodemim.com"
  },
  {
    "id": "new-sheet-26",
    "name": "Tudo de Tudo Pet",
    "segment": "Serviços",
    "location": "Belém - PA",
    "phone": "91982716874",
    "email": null,
    "site": null,
    "instagram": null,
    "priority": "Alta",
    "score": 72,
    "pain": "A investigar",
    "opportunity": "Landing page/site + captação via WhatsApp",
    "initials": "TD",
    "color": "orange",
    "service": "Landing page/site + captação via WhatsApp",
    "demo": false,
    "source": "petshoppertodemim.com"
  },
  {
    "name": "Norte Refrigeração",
    "segment": "Serviços",
    "location": "Estrada do Tapanã, 8 - Belém - PA",
    "phone": "9132784851",
    "whatsapp": "3121802841",
    "site": "https://www.norterefrigeracao.com.br/atendimento",
    "instagram": "@norterefrigeracao",
    "source": "https://www.norterefrigeracao.com.br/atendimento",
    "opportunity": "Catálogo B2B e operação comercial para refrigeração",
    "id": "new-verified-27",
    "email": null,
    "priority": "Alta",
    "score": 88,
    "pain": "A investigar",
    "initials": "NR",
    "color": "cyan",
    "service": "Catálogo B2B e operação comercial para refrigeração",
    "demo": false
  },
  {
    "name": "Santa Marta Distribuidora",
    "segment": "Distribuidoras",
    "location": "Estr. da Vila Nova, 236 - Cidade Nova, Ananindeua - PA",
    "phone": "9132015800",
    "whatsapp": "9132015800",
    "site": "https://santamartadistribuidora.com.br/",
    "instagram": "@santamarta.dist",
    "source": "https://santamartadistribuidora.com.br/",
    "opportunity": "Catálogo B2B + orçamento + pedidos",
    "id": "new-verified-28",
    "email": null,
    "priority": "Alta",
    "score": 88,
    "pain": "A investigar",
    "initials": "SM",
    "color": "pink",
    "service": "Catálogo B2B + orçamento + pedidos",
    "demo": false
  },
  {
    "name": "Bourbon Distribuidora",
    "segment": "Distribuidoras",
    "location": "BR 316 - KM 03 - Passagem São Pedro, Galpão 4 - Coqueiro, Ananindeua - PA",
    "phone": "9137228211",
    "whatsapp": "91984082069",
    "site": "https://bourbondistribuidora.com.br/contatos/",
    "instagram": "@bourbondistribuidora",
    "source": "https://bourbondistribuidora.com.br/contatos/",
    "opportunity": "Catálogo B2B + orçamento + pedidos",
    "id": "new-verified-29",
    "email": null,
    "priority": "Alta",
    "score": 88,
    "pain": "A investigar",
    "initials": "BD",
    "color": "violet",
    "service": "Catálogo B2B + orçamento + pedidos",
    "demo": false
  },
  {
    "name": "Depósito MG Distribuidora de Água",
    "segment": "Distribuidoras",
    "location": "Belém - PA",
    "phone": "9130875781",
    "whatsapp": "91980956575",
    "site": null,
    "instagram": "@mgdistribuidoradeagua",
    "source": "https://www.instagram.com/mgdistribuidoradeagua/",
    "opportunity": "Catálogo local + pedidos via WhatsApp",
    "id": "new-verified-30",
    "email": null,
    "priority": "Alta",
    "score": 88,
    "pain": "A investigar",
    "initials": "DM",
    "color": "blue",
    "service": "Catálogo local + pedidos via WhatsApp",
    "demo": false
  },
  {
    "name": "Salomão Mendes Imóveis",
    "segment": "Imobiliárias",
    "location": "Belém - PA",
    "phone": "91981478844",
    "whatsapp": "91981478844",
    "site": "https://www.salomaomendesimoveis.com.br/",
    "instagram": null,
    "source": "https://www.salomaomendesimoveis.com.br/",
    "opportunity": "Apresentação digital de imóveis e captação de interessados",
    "id": "new-verified-31",
    "email": null,
    "priority": "Alta",
    "score": 88,
    "pain": "A investigar",
    "initials": "SM",
    "color": "lime",
    "service": "Apresentação digital de imóveis e captação de interessados",
    "demo": false
  }
] as const;
